### ISSUE TITLE
how to train a new model

### ISSUE THREAD

**Issue by yipukangda** [yukiteruono/pbsim2#17]
HI,

If I have some raw data from a new sequencing system, how could train a specific HMM model for these data.

Thank

**Comment by yukiteruono** [comment]
Thank you for your using PBSIM.
The building of error or quality score model is not yet fully automated. 
It is not yet possible to provide model building tools to users.

**Comment by yipukangda** [comment]
@yukiteruono I see, is there any plan for adding this function or I can train a model manually from another way.  btw, do HMM model conflict with the argument `--difference-ratio` for error rate allocations, Thanks.

**Comment by yukiteruono** [comment]
There is a plan to automate and publish tools for building HMM models, but the plan is a low priority for us.
The error ratio is built into error models, so --difference-ratio has no effect when using the error models.
We plan to publish the model built using the latest Nanopore read on PBSIM3 in the near future.

**Comment by yipukangda** [comment]
@yukiteruono ok, I will follow the progression of PBSIM3, thanks.
