### ISSUE TITLE
Can‘t find makefile

### ISSUE THREAD

**Issue by aLin-07** [yukiteruono/pbsim2#18]
Hello, I am a beginner. After I unzip the git package, I can't find the makefile file after typing./config and make in the LINUX terminal. What is the reason for this?
<img width="312" alt="terminal issue" src="https://github.com/yukiteruono/pbsim2/assets/49394172/db338a07-3e96-4ef0-b14b-3fc07dd106c9">

**Comment by yukiteruono** [comment]
Thank you for your interest in PBSIM2. 
The output of configure shows that no compilers such as g++ are found. Installing a compiler may solve the problem. In any case, this is not a problem specific to PBSIM2.

**Comment by aLin-07** [comment]
Ok, thank you, I have solved that problem
