### ISSUE TITLE
HMM model for HiFi reads

### ISSUE THREAD

**Issue by sinamajidian** [yukiteruono/pbsim2#5]
Dear pbsim2 team

I'm wondering whether you have provided the HMM model for HiFi reads of PacBio. Maybe one of the models in the `data` folder is related to HiFi or CCS?  
```
P4C2.model  P5C3.model  P6C4.model  R103.model  R94.model   R95.model   
``` 

Thank you in advance.
Sina

**Comment by yukiteruono** [comment]
Thank you for your using PBSIM2.
At the moment, we do not provide the HMM model for HiFi reads. 
We are developing a method for simulating HiFi reads and will implement it in PBSIM2 in the near future.

**Comment by sinamajidian** [comment]
Thanks for your respond. 
Looking forward to using that.

**Comment by pesho-ivanov** [comment]
dear @yukiteruono, thank you for working on simulating the new technologies!
meantime, could you recommend a reasonable way to generate HiFi reads, possibly using other tools?
