### ISSUE TITLE
Option for number of reads?

### ISSUE THREAD

**Issue by ChristosMatzoros** [yukiteruono/pbsim2#7]
Hello,

Is there any option to select the number of created reads as a whole? I use a multi-fasta file as a reference and it seems that pbsim creates an arbitrary number of reads for each FASTA.

Thanks,
Chris

**Comment by yukiteruono** [comment]
Thank you for your using PBSIM2.
PBSIM2 does not have an option to select the number of create reads as a whole.
You cannot specify the number of reads, but you can use the --depth option to specify the total amount of reads.
Simulated reads are randomly sampled from a reference sequence. If the reference is multi-fasta file, the number of reads generated from each reference sequence is roughly proportional to its sequence size.

**Comment by ChristosMatzoros** [comment]
Thank you
